### ISSUE TITLE
do a new iteration of parcellation of oscillation results

### ISSUE THREAD

**Issue by schoffelen** [schoffelen/MOUS#75]
As discussed on Nov 3, 2014, to make sense of the beamformer results, the spatial clusters need to be broken up in smaller (functional) units. It was discussed to go back to a parcellation scheme, and do the statistics in time bins. Contrary to what was stated, we don't have yet the same parcellation scheme in volumetric space as we have them in surface space. The conte69 atlas based sub-parcellation therefore needs to be made. Alternatively, we could recompute all oscillation results onto the cortical sheet. Added advantage of the latter would be that the parcellation + visualization would be really straightforward. Disadvantage would be the need for recomputation of all results.

**Comment by schoffelen** [comment]
The new issue referred to is #83 .

@nihll I guess that this issue can be closed as well. It seems that the bottom line is that overall the story will not change much from when looking at the original volumetric non-parcellated results. It has been decided that Nietzsche is going to finalize her thesis chapter using those analyses, with visualization on the cortical sheet using workbench.

Perhaps it would be good to document what you did briefly here, and then close this issue

**Comment by nihll** [comment]
Action point  #1: try the parcellation scheme 
Action point  #2: use workbench to visualize results 

•	Average across relevant time bins prior to interpolation
•	Interpolate volumetric data (5782 voxels) into cortical sheet (8916 vertices)
•	Parcellate cortical sheet results 
•	Perform statistics
        Using FieldTrip, the main parameters used were
         	cfg.method = ‘montecarlo’ 
         	cfg.correctm = ‘max’;   other options tried which yielded no/less effects

Outcome
-	Overall, the parcellation did not yield improved results
o	For the results shown below we tried 5 different types of parameters
o	For comparison we use 0-0.5s , and then 0.25, 0.35 and 0.45s, the latter was indeed better as suggested in the MOUS meeting
	Importantly, each time point is not an instantaneous estimates in time because of the time window used to analyze; e.g., 0.25  is 0.2
	sliding window of 400ms for 5Hz, and 250ms for all higher frequencies
o	1) use cfg.correctm = ‘max’ ;  ‘cluster’ yielded no results in gamma
o	2) individual test for each frequency band (5, 10, 16,40-68, 80-100 Hz)
	No significant results
o	3) concatenate frequencies into one matrix in a horizontal manner (along time dimension)
	Few significant results: occipital cortex (which has strongest power)
o	4) concatenate frequencies into matrix in a vertical manner (along channel dimension)
